/*
 * Alipay.com Inc.
 * Copyright (c) 2004 - 2010 All Rights Reserved.
 * Powered By [rapid-generator]
 */
package com.iacthink.dal.daointerface;

import java.util.List;

import org.springframework.dao.DataAccessException;

import com.iacthink.dal.dataobject.StudentDO;



/**
 * StudentDAO
 * database table: student
 * database table comments: Student
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/dalgen</tt>
 * @author badqiu(zhongxuan)
 *
 
 */
public interface StudentDAO {


	/**
	 * 
	 * sql:
	 * <pre>SELECT         id, s_no, s_name,s_age           FROM         student</pre> 
	 */
	public List<StudentDO> queryAll() throws DataAccessException;

	/**
	 * 
	 * sql:
	 * <pre>insert      into         student         (id,s_no,s_name,s_age)     values         (?,?,?,?)</pre> 
	 */
	public int insert(StudentDO student) throws DataAccessException;

}



