/*
 * Alipay.com Inc.
 * Copyright (c) 2004 - 2010 All Rights Reserved.
 * Powered By [rapid-generator]
 */

package com.iacthink.dal.dataobject;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;


import java.io.*;
import java.net.*;
import java.util.*;

import java.math.BigDecimal;
import java.math.BigInteger;



/**
 * StudentDO
 * database table: student
 * database table comments: Student
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/dalgen</tt>
 * @author badqiu(zhongxuan)
 *
 
 */
public class StudentDO implements java.io.Serializable {
	private static final long serialVersionUID = -5216457518046898601L;
	
	/**
	 * id 		db_column: id 
	 */
	private int id;
	/**
	 * sno 		db_column: s_no 
	 */
	private String sno;
	/**
	 * sname 		db_column: s_name 
	 */
	private String sname;
	/**
	 * sage 		db_column: s_age 
	 */
	private int sage;

	
	public void setId(int id) {
		this.id = id;
	}
	
	public int getId() {
		return this.id;
	}
	
	public void setSno(String sno) {
		this.sno = sno;
	}
	
	public String getSno() {
		return this.sno;
	}
	
	public void setSname(String sname) {
		this.sname = sname;
	}
	
	public String getSname() {
		return this.sname;
	}
	
	public void setSage(int sage) {
		this.sage = sage;
	}
	
	public int getSage() {
		return this.sage;
	}

	public String toString() {
		return new ToStringBuilder(this)
			.append("Id",getId())
			.append("Sno",getSno())
			.append("Sname",getSname())
			.append("Sage",getSage())
			.toString();
	}
	
	public int hashCode() {
		return new HashCodeBuilder()
			.append(getId())
			.toHashCode();
	}
	
	public boolean equals(Object obj) {
		if(obj == null) return false;
		if(this == obj) return true;
		if(obj instanceof StudentDO == false) return false;
		StudentDO other = (StudentDO)obj;
		return new EqualsBuilder()
			.append(getId(),other.getId())
			.isEquals();
	}
}

